# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_library")

oncall("data_compression")

zs_library(
    name = "safetensors_parser",
    srcs = glob(
        ["*.c"],
        exclude = ["tests/*"],
    ),
    headers = glob(
        ["*.h"],
    ),
    exported_deps = [
        "../..:zstronglib",
    ],
)
