// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * SDDL2 Auto-Generated Bytecode Test Framework
 *
 * This framework automatically discovers and runs all .asm test files
 * without requiring manual code changes to the test file.
 *
 * Features:
 * - Auto-discovery: Every .asm file in the asm/ directory becomes a test
 * - Metadata-driven: Tests use metadata from assembly comments
 * - Custom validators: Tests can specify custom validation functions
 * - No boilerplate: Default validation handles most cases
 *
 * Usage:
 * 1. Add a new .asm file to tests/compress/graphs/sddl2/asm/
 * 2. Include test metadata in comments:
 *      # Test: <description>
 *      # Expected: <SDDL2_ERROR_CODE>  (optional, defaults to SDDL2_OK)
 *      # Custom: <validator_function>  (optional)
 * 3. Run: python3 tests/compress/graphs/sddl2/generate_test_bytecode.py
 * 4. Build and run this test executable
 *
 * The test will automatically:
 * - Execute the bytecode
 * - Verify the expected error code
 * - Call custom validators if specified
 * - Report detailed pass/fail status
 */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "generated_test_bytecode.h"
#include "openzl/compress/graphs/sddl2/sddl2_interpreter.h"

/* Test statistics */
static struct {
    int total;
    int passed;
    int failed;
    int skipped;
} test_stats = { 0, 0, 0, 0 };

/**
 * Custom validator function type
 *
 * Custom validators can perform additional checks beyond error code validation.
 * They receive the test case, execution result, and segment list.
 *
 * Return:
 *   0 = validation passed
 *   non-zero = validation failed
 */
typedef int (*CustomValidator)(
        const SDDL2_TestCase* test,
        SDDL2_Error result,
        const SDDL2_Segment_list* segments);

/**
 * Default validator: checks error code only
 */
static int default_validator(
        const SDDL2_TestCase* test,
        SDDL2_Error result,
        const SDDL2_Segment_list* segments)
{
    (void)segments; // Unused

    if (result != test->expected_error) {
        fprintf(stderr,
                "  ❌ Expected error %d, got %d\n",
                test->expected_error,
                result);
        return 1;
    }

    return 0;
}

/**
 * Execute a single test case
 */
static void run_test_case(const SDDL2_TestCase* test)
{
    test_stats.total++;

    printf("Test %3d: %-50s ", test_stats.total, test->name);

    // Check if test should be skipped
    if (test->skip) {
        printf("⊘ (skipped)\n");
        test_stats.skipped++;
        return;
    }

    // Execute bytecode
    SDDL2_Segment_list segments;
    SDDL2_Segment_list_init(&segments, NULL, NULL);

    // Allocate input data if needed
    uint8_t* input = NULL;
    uint8_t static_input[1024]; // Stack allocation for small inputs
    uint8_t* heap_input = NULL; // Heap allocation for large inputs
    size_t input_size   = test->input_size;

    if (input_size > 0) {
        if (input_size <= sizeof(static_input)) {
            // Use stack allocation for small inputs
            input = static_input;
        } else {
            // Use heap allocation for large inputs
            heap_input = (uint8_t*)malloc(input_size);
            if (!heap_input) {
                printf("✗ (failed to allocate %zu bytes)\n", input_size);
                test_stats.failed++;
                SDDL2_Segment_list_destroy(&segments);
                return;
            }
            input = heap_input;
        }

        // Fill with test data (simple pattern: 0, 1, 2, ...)
        for (size_t i = 0; i < input_size; i++) {
            input[i] = (uint8_t)(i & 0xFF);
        }
    } else {
        // No input needed
        input      = static_input;
        input_size = 0;
    }

    SDDL2_Error result = SDDL2_execute_bytecode(
            test->bytecode, test->size, input, input_size, &segments);

    // Select validator (custom or default)
    CustomValidator validator = default_validator;
    if (test->custom_validator != NULL) {
        // TODO: Implement custom validator lookup table
        // For now, fall back to default
        validator = default_validator;
    }

    // Run validation
    int validation_result = validator(test, result, &segments);

    // Cleanup
    if (heap_input) {
        free(heap_input);
    }
    SDDL2_Segment_list_destroy(&segments);

    // Report result
    if (validation_result == 0) {
        printf("✓\n");
        test_stats.passed++;
    } else {
        printf("✗\n");
        if (test->description[0]) {
            fprintf(stderr, "  Description: %s\n", test->description);
        }
        fprintf(stderr,
                "  Expected: %d, Got: %d\n",
                test->expected_error,
                result);
        test_stats.failed++;
    }
}

/**
 * Run all auto-discovered tests
 */
static void run_all_tests(void)
{
    printf("=== SDDL2 Auto-Generated Bytecode Tests ===\n");
    printf("Running %zu auto-discovered tests from .asm files\n\n",
           SDDL2_BYTECODE_TEST_COUNT);

    for (size_t i = 0; i < SDDL2_BYTECODE_TEST_COUNT; i++) {
        run_test_case(&SDDL2_BYTECODE_TESTS[i]);
    }

    printf("\n=== Test Summary ===\n");
    printf("Total:   %d\n", test_stats.total);
    printf("Passed:  %d\n", test_stats.passed);
    printf("Failed:  %d\n", test_stats.failed);
    printf("Skipped: %d\n", test_stats.skipped);

    if (test_stats.failed > 0) {
        printf("\n❌ FAILED: %d/%d tests failed\n",
               test_stats.failed,
               test_stats.total);
    } else {
        printf("\n✅ SUCCESS: All %d tests passed!\n", test_stats.passed);
    }
}

/**
 * Optional: Run tests by pattern/filter
 */
static void run_filtered_tests(const char* pattern)
{
    printf("=== SDDL2 Filtered Tests (pattern: %s) ===\n\n", pattern);

    int matched = 0;
    for (size_t i = 0; i < SDDL2_BYTECODE_TEST_COUNT; i++) {
        if (strstr(SDDL2_BYTECODE_TESTS[i].name, pattern) != NULL) {
            run_test_case(&SDDL2_BYTECODE_TESTS[i]);
            matched++;
        }
    }

    printf("\n=== Test Summary ===\n");
    printf("Matched: %d/%zu tests\n", matched, SDDL2_BYTECODE_TEST_COUNT);
    printf("Passed:  %d\n", test_stats.passed);
    printf("Failed:  %d\n", test_stats.failed);

    if (test_stats.failed > 0) {
        printf("\n❌ FAILED: %d/%d tests failed\n", test_stats.failed, matched);
    } else {
        printf("\n✅ SUCCESS: All %d matched tests passed!\n", matched);
    }
}

int main(int argc, char* argv[])
{
    if (argc > 1) {
        // Run filtered tests by pattern
        run_filtered_tests(argv[1]);
    } else {
        // Run all tests
        run_all_tests();
    }

    return (test_stats.failed == 0) ? 0 : 1;
}
