// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_DICT_BUNDLE_H
#define OPENZL_DICT_BUNDLE_H

#include "openzl/common/allocation.h"
#include "openzl/zl_errors.h"
#include "openzl/zl_opaque_types.h"

#if defined(__cplusplus)
extern "C" {
#endif

// ============================================================================
// ZL_BundleInfo - Metadata about the bundle and associated dicts
// ============================================================================

/**
 * Packed wire format for a serialized BundleInfo.
 *
 *   offset  size   field
 *   ------  -----  ------------------------------------------------
 *     0       4    magic       – 32-bit LE, must be 0x4942CCDA
 *     4      32    bundleID    – 256-bit LE ZL_DictBundleID
 *    36       1    isFatBundle - 0 for standalone bundle info, 1 if the parser
 *                                should additionally expect to find the
 *                                constituent dicts attached to the info
 *    37       4    numDicts    – 32-bit LE number of dictionaries
 *    41    N*32    dictIDs     – array of N ZL_DictID (each 256-bit LE)
 *
 *   Total packed size = 41 + numDicts * 32
 *
 * A "fat bundle" consists of a packed BundleInfo followed by a
 * concatenation of all constituent packed dicts.
 */
typedef struct {
    ZL_BundleID bundleID;
    bool isFatBundle;
    size_t numDicts;
    ZL_DictID* dictIDs;
} ZL_BundleInfo;
typedef const ZL_BundleInfo* ZL_BundleInfoConstPtr;
ZL_RESULT_DECLARE_TYPE(ZL_BundleInfoConstPtr);

/**
 * Parse a packed bundle info struct into the provided ZL_BundleInfo.
 * @return the packed size of the bundle info.
 */
ZL_Report BundleInfo_parse(
        ZL_BundleInfo* info,
        const void* bundleContent,
        size_t bundleSize,
        Arena* allocator);

ZL_Report
BundleInfo_pack(void* dst, size_t dstCapacity, const ZL_BundleInfo* info);

// ============================================================================
// ZL_DictBundle - A bundle of dictionaries
// ============================================================================

// A non-owning "view" of a bundle. The backing memory must be managed by an
// external allocator.
struct ZL_DictBundle_s {
    ZL_BundleInfo info;
    size_t packedSize; // size of the bundle on wire, incl. packed info and all
                       // packed dicts
    const ZL_Dict** dicts;
};

typedef const ZL_DictBundle* ZL_DictBundleConstPtr;
ZL_RESULT_DECLARE_TYPE(ZL_DictBundleConstPtr);

/**
 * Takes an array of pre-packed packed dictionary content (generated by
 * training) and packs it into a single "fat" bundle blob containing the
 * ZL_BundleInfo, followed by a concatenation of all the packed dicts.
 *
 * @pre @p dicts are well-formed packed dicts generated using ZL_Dict_pack().
 */
ZL_Report ZL_DictBundle_packFatBundle(
        void* dst,
        size_t dstCapacity,
        const void** dicts,
        size_t* dictSizes,
        size_t numDicts);

/**
 * Parses a fat bundle generated by ZL_DictBundle_packFatBundle().
 * @param allocator an arena to use for bundle/dict creation.
 * @return a dict bundle, a structure containing pointers to the arena-allocated
 * info and dicts. The memory for the bundle is managed by the arena.
 */
ZL_RESULT_OF(ZL_DictBundleConstPtr)
ZL_DictBundle_parseFatBundle(
        const void* bundleContent,
        size_t bundleSize,
        Arena* allocator);

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // OPENZL_DICT_BUNDLE_H
