// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_ZL_DICT_H
#define OPENZL_ZL_DICT_H

#include <stddef.h> // size_t
#include <stdint.h> // uint8_t
#include "openzl/zl_common_types.h"
#include "openzl/zl_errors.h"       // ZL_RESULT_OF
#include "openzl/zl_localParams.h"  // ZL_LocalParams
#include "openzl/zl_opaque_types.h" // ZL_Dict
#include "openzl/zl_portability.h"  // ZL_NOEXCEPT_FUNC_PTR

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * ================================== ZL_Dict ==================================
 *
 * The ZL_Dict is a dictionary object for use with both the encoder and decoder.
 * Dictionaries are only supported for codecs. Dictionaries are also
 * instance-specific. Two copies of the same codec within the same graph can
 * have different associated dictionaries. The ZL_Dict APIs are exposed for
 * *creating* dictionaries and are likely not what you are looking for. See the
 * ZL_DictLoader for how to *use* dictionaries.
 */

typedef struct {
    uint8_t bytes[32];
} ZL_DictID;

/**
 * Helper function to pack a serialized dict buffer into the ZL_Dict wire
 * format.
 * @param dst the buffer to write the serialized dict into. The size must be
 * larger than the @p src size by at least 60 bytes.
 * @param codecID the codec associated with this dict.
 * @return on success,the resulting serialized size. Otherwise, an error.
 */
ZL_Report ZL_Dict_pack(
        void* dst,
        size_t dstCapacity,
        ZL_IDType codecID,
        const void* src,
        size_t srcSize);

typedef ZL_Dict* ZL_DictPtr;
ZL_RESULT_DECLARE_TYPE(ZL_DictPtr);

/*
 * =============================== ZL_DictBundle ===============================
 *
 * The ZL_DictBundle contains information about all the ZL_Dict objects required
 * by a particular compressor. Note that any individual frame generated by a
 * compressor may not require every single dictionary in the bundle to
 * (de)compress. However, if it is *possible* for a frame to require a dict
 * object to decompress, it must be recorded in the bundle.
 */

typedef struct {
    uint8_t bytes[32];
} ZL_DictBundleID;

typedef struct {
    ZL_DictBundleID bundleID;
    size_t numDicts;
    ZL_DictID* dicts;
} ZL_DictBundle;

typedef ZL_DictBundle* ZL_DictBundlePtr;
ZL_RESULT_DECLARE_TYPE(ZL_DictBundlePtr);

/**
 * Helper function to pack a list of dict IDs into the ZL_DictBundle wire
 * format.
 * @param dst the buffer to write the serialized bundle into. The size must be
 * larger than the byte size of @p dictIDs by at least 48 bytes.
 */
ZL_Report
ZL_DictBundle_serialize(void* dst, size_t dstCapacity, ZL_DictBundle* bundle);

/*
 * =============================== ZL_DictLoader ===============================
 *
 * The ZL_DictLoader is responsible for fetching and (de)materializing dicts and
 * bundles. It is used by both the ZL_Compressor/ZL_CCtx and ZL_DCtx to provide
 * dictionary functionality.
 *
 * The fetching APIs are provided unimplemented to enable you to customize blob
 * sources and caching behavior. (A simple reference implementation is also
 * provided in ZL_StaticSetDictLoader. This is sufficient for use with a static
 * set of known dictionaries and bundles.)
 *
 * Before usage, individual codec de/materializers must be registered with the
 * ZL_DictLoader.
 */
typedef struct {
    void* opaque; // optional opaque pointer. The ZL_DictLoader will take
                  // ownership of this pointer.
    void (*freeOpaque)(
            void* opaque); // Function to free the opaque pointer, if provided.
    /**
     * Functions to fetch bundles and dicts. Implementors are expected to use
     * the TODO helper functions to parse raw blobs. Implementors are encouraged
     * to cache bundles and dicts using a custom state stored in @p opaque .
     */
    ZL_RESULT_OF(ZL_DictBundlePtr) (
            *fetchDictBundle)(void* opaque, const ZL_DictBundleID* id);
    ZL_RESULT_OF(ZL_DictPtr) (*fetchDict)(void* opaque, const ZL_DictID* id);
} ZL_DictLoaderDesc;

ZL_DictLoader* ZL_DictLoader_create(const ZL_DictLoaderDesc* desc);
void ZL_DictLoader_free(ZL_DictLoader* loader);

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // OPENZL_ZL_DICT_H
