// Copyright (c) Meta Platforms, Inc. and affiliates.
/**
 * Integration tests for SDDL2_parse() type conversion functionality.
 *
 * These tests verify that SDDL2_parse() correctly converts typed segments
 * from Serial to Numeric format based on their type kind (U8, I32LE, etc.),
 * and that BYTES segments remain as Serial.
 *
 * The tests use pre-assembled SDDL2 bytecode files generated by
 * tools/sddl/assembler/sddl2_assembler.py from .asm source files.
 * Assembly source is included in comments for documentation.
 *
 * FUTURE IMPROVEMENT:
 * Currently, bytecode must be generated externally using the Python assembler,
 * which creates a disconnect between the test and its assembly source.
 * A potential improvement would be to implement a C version of the SDDL2
 * assembler that could be used directly in tests, allowing assembly source
 * to be embedded as string literals and assembled at runtime:
 *
 *     const char* assembly = R"(
 *         push.u64 10
 *         push.type U8
 *         segment.create_tagged
 *         halt
 *     )";
 *     auto bytecode = SDDL2_assemble(assembly);
 *
 * This would improve maintainability and make the relationship between
 * test intent and bytecode clearer, eliminating the manual pre-compilation
 * step when opcodes change.
 */

#include <array>
#include <cstring>

#include <gtest/gtest.h>

#include "openzl/zl_compress.h"
#include "openzl/zl_compressor.h"
#include "openzl/zl_decompress.h"
#include "openzl/zl_graph_api.h"
#include "openzl/zl_localParams.h"

extern "C" {
#include "openzl/compress/graphs/sddl2/sddl2.h"
}

namespace {

/**
 * Load bytecode from file
 */
static std::vector<uint8_t> load_bytecode(const char* filename)
{
    FILE* f = fopen(filename, "rb");
    if (!f) {
        throw std::runtime_error(std::string("Failed to open ") + filename);
    }

    // Get file size
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size < 0) {
        fclose(f);
        throw std::runtime_error("Failed to get file size");
    }

    // Read bytecode
    std::vector<uint8_t> bytecode(static_cast<size_t>(size));
    size_t bytes_read = fread(bytecode.data(), 1, static_cast<size_t>(size), f);
    fclose(f);

    if (bytes_read != static_cast<size_t>(size)) {
        throw std::runtime_error("Failed to read complete file");
    }

    return bytecode;
}

/**
 * Compress using SDDL2_parse with bytecode parameter
 */
static size_t compress_sddl2(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        const void* bytecode,
        size_t bytecode_size)
{
    assert(dstCapacity >= ZL_compressBound(srcSize));

    ZL_CCtx* const cctx = ZL_CCtx_create();
    assert(cctx);

    // Set format version (required parameter)
    ZL_Report const fvr = ZL_CCtx_setParameter(
            cctx, ZL_CParam_formatVersion, ZL_MAX_FORMAT_VERSION);
    EXPECT_EQ(ZL_isError(fvr), 0) << "Failed to set format version";

    ZL_Compressor* const cgraph = ZL_Compressor_create();
    assert(cgraph);

    // Register SDDL2_parse with bytecode as local parameter
    ZL_RefParam bytecodeParam = { SDDL2_BYTECODE_PARAM,
                                  bytecode,
                                  bytecode_size };

    ZL_LocalRefParams refParams = { .refParams   = &bytecodeParam,
                                    .nbRefParams = 1 };

    ZL_LocalParams params = { .intParams = { nullptr, 0 },
                              .refParams = refParams };

    ZL_Type inputType                     = ZL_Type_serial;
    ZL_FunctionGraphDesc const sddl2_desc = { .name           = "sddl2_parse",
                                              .graph_f        = SDDL2_parse,
                                              .inputTypeMasks = &inputType,
                                              .nbInputs       = 1,
                                              .lastInputIsVariable = false,
                                              .localParams         = params };

    ZL_GraphID sddl2_gid =
            ZL_Compressor_registerFunctionGraph(cgraph, &sddl2_desc);
    EXPECT_NE(sddl2_gid.gid, ZL_GRAPH_ILLEGAL.gid)
            << "Failed to register SDDL2_parse";

    ZL_Report const rcgr = ZL_CCtx_refCompressor(cctx, cgraph);
    EXPECT_EQ(ZL_isError(rcgr), 0) << "CGraph reference failed\n";

    ZL_Report const r = ZL_CCtx_compress(cctx, dst, dstCapacity, src, srcSize);
    if (ZL_isError(r)) {
        const char* errCtx = ZL_CCtx_getErrorContextString(cctx, r);
        EXPECT_EQ(ZL_isError(r), 0) << "compression failed\nError context: "
                                    << (errCtx ? errCtx : "none");
        ZL_Compressor_free(cgraph);
        ZL_CCtx_free(cctx);
        return 0;
    }

    ZL_Compressor_free(cgraph);
    ZL_CCtx_free(cctx);

    return ZL_validResult(r);
}

/**
 * Decompress
 */
static size_t
decompress(void* dst, size_t dstCapacity, const void* src, size_t srcSize)
{
    ZL_Report const dr = ZL_getDecompressedSize(src, srcSize);
    assert(!ZL_isError(dr));
    size_t const dstSize = ZL_validResult(dr);
    assert(dstCapacity >= dstSize);
    (void)dstSize;

    ZL_DCtx* const dctx = ZL_DCtx_create();
    assert(dctx);

    ZL_Report const r =
            ZL_DCtx_decompress(dctx, dst, dstCapacity, src, srcSize);
    EXPECT_EQ(ZL_isError(r), 0) << "decompression failed \n";

    ZL_DCtx_free(dctx);

    return ZL_validResult(r);
}

/**
 * Round-trip test helper
 */
static void roundtrip_test(
        const void* input,
        size_t inputSize,
        const void* bytecode,
        size_t bytecode_size,
        const char* testName)
{
    size_t const compressedBound = ZL_compressBound(inputSize);
    void* const compressed       = malloc(compressedBound);
    assert(compressed);

    size_t const compressedSize = compress_sddl2(
            compressed,
            compressedBound,
            input,
            inputSize,
            bytecode,
            bytecode_size);
    EXPECT_GT(compressedSize, 0u) << testName << ": compression returned 0";

    void* const decompressed = malloc(inputSize);
    assert(decompressed);

    size_t const decompressedSize =
            decompress(decompressed, inputSize, compressed, compressedSize);
    EXPECT_EQ(decompressedSize, inputSize)
            << testName << ": decompressed size mismatch";

    EXPECT_EQ(std::memcmp(decompressed, input, inputSize), 0)
            << testName << ": decompressed data doesn't match input";

    free(decompressed);
    free(compressed);
}

/**
 * Test: Single U8 typed segment
 *
 * Assembly source (test_data/single_u8_segment.asm):
 *   push.tag 0
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 *
 * Bytecode must be assembled before running this test:
 *   python3 tools/sddl/assembler/sddl2_assembler.py \
 *     tests/round_trip/test_data/single_u8_segment.asm \
 *     tests/round_trip/test_data/single_u8_segment.bin
 */
TEST(SDDL2ParseTest, SingleU8Segment)
{
    auto bytecode =
            load_bytecode("tests/round_trip/test_data/single_u8_segment.bin");
    std::array<uint8_t, 4> input = { 0xAA, 0xBB, 0xCC, 0xDD };

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "SingleU8Segment");
}

/**
 * Test: Single I32LE typed segment
 *
 * Assembly source (test_data/single_i32le_segment.asm):
 *   push.tag 100
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2ParseTest, SingleI32LESegment)
{
    auto bytecode = load_bytecode(
            "tests/round_trip/test_data/single_i32le_segment.bin");
    std::array<uint8_t, 4> input = { 0x2A, 0x00, 0x00, 0x00 }; // 42 in LE

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "SingleI32LESegment");
}

/**
 * Test: BYTES segment (no conversion)
 *
 * Assembly source (test_data/bytes_segment.asm):
 *   push.i32 5
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2ParseTest, BytesSegmentNoConversion)
{
    auto bytecode =
            load_bytecode("tests/round_trip/test_data/bytes_segment.bin");
    std::array<uint8_t, 5> input = { 'H', 'e', 'l', 'l', 'o' };

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "BytesSegmentNoConversion");
}

/**
 * Test: Mixed type segments (U8, I32LE, BYTES)
 *
 * Assembly source (test_data/mixed_segments.asm):
 *   # Segment 1: U8[4]
 *   push.tag 1
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *
 *   # Segment 2: I32LE[1]
 *   push.tag 2
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *
 *   # Segment 3: BYTES[4]
 *   push.i32 4
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2ParseTest, MixedTypeSegments)
{
    auto bytecode =
            load_bytecode("tests/round_trip/test_data/mixed_segments.bin");
    std::array<uint8_t, 12> input = {
        0xAA, 0xBB, 0xCC, 0xDD, // Segment 1
        0x2A, 0x00, 0x00, 0x00, // Segment 2
        0x01, 0x02, 0x03, 0x04  // Segment 3
    };

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "MixedTypeSegments");
}

/**
 * Test: U16BE big-endian segment
 *
 * Assembly source (test_data/u16be_segment.asm):
 *   push.tag 50
 *   push.type.u16be
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2ParseTest, U16BESegmentBigEndian)
{
    auto bytecode =
            load_bytecode("tests/round_trip/test_data/u16be_segment.bin");
    std::array<uint8_t, 8> input = { 0x12, 0x34, 0x56, 0x78,
                                     0xAB, 0xCD, 0xEF, 0x01 };

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "U16BESegmentBigEndian");
}

/**
 * Test: Array type segment (U32LE[10])
 *
 * Tests the type.fixed_array opcode in end-to-end compression/decompression.
 * This validates that array types correctly integrate with SDDL2_parse and
 * that segment size calculation accounts for the array width field.
 *
 * Assembly source (test_data/array_type_u32le_10.asm):
 *   push.tag 100
 *   push.type.u32le
 *   type.fixed_array 10
 *   push.i32 10
 *   segment.create_tagged
 *   halt
 *
 * This creates a segment with type U32LE[10]:
 *   - kind: SDDL2_TYPE_U32LE
 *   - width: 10
 *   - Total size: 10 elements × 4 bytes/element = 40 bytes
 */
TEST(SDDL2ParseTest, ArrayTypeU32LE10)
{
    auto bytecode =
            load_bytecode("tests/round_trip/test_data/array_type_u32le_10.bin");

    // 10 U32LE values in little-endian format
    std::array<uint8_t, 40> input = { // Value 0
                                      0x00,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 1
                                      0x01,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 2
                                      0x02,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 3
                                      0x03,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 4
                                      0x04,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 5
                                      0x05,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 6
                                      0x06,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 7
                                      0x07,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 8
                                      0x08,
                                      0x00,
                                      0x00,
                                      0x00,
                                      // Value 9
                                      0x09,
                                      0x00,
                                      0x00,
                                      0x00
    };

    roundtrip_test(
            input.data(),
            input.size(),
            bytecode.data(),
            bytecode.size(),
            "ArrayTypeU32LE10");
}

} // namespace
