// Copyright (c) Meta Platforms, Inc. and affiliates.
/**
 * Integration tests for SDDL2_parse() type conversion functionality.
 *
 * These tests verify that SDDL2_parse() correctly converts typed segments
 * from Serial to Numeric format based on their type kind (U8, I32LE, etc.),
 * and that BYTES segments remain as Serial.
 *
 * The tests use pre-assembled SDDL2 bytecode files generated by
 * tools/sddl/assembler/sddl2_assembler.py from .asm source files.
 * Assembly source is included in comments for documentation.
 *
 * FUTURE IMPROVEMENT:
 * Currently, bytecode must be generated externally using the Python assembler,
 * which creates a disconnect between the test and its assembly source.
 * A potential improvement would be to implement a C version of the SDDL2
 * assembler that could be used directly in tests, allowing assembly source
 * to be embedded as string literals and assembled at runtime:
 *
 *     const char* assembly = R"(
 *         push.u64 10
 *         push.type U8
 *         segment.create_tagged
 *         halt
 *     )";
 *     auto bytecode = SDDL2_assemble(assembly);
 *
 * This would improve maintainability and make the relationship between
 * test intent and bytecode clearer, eliminating the manual pre-compilation
 * step when opcodes change.
 */

#include <array>
#include <cstring>

#include <gtest/gtest.h>

#include "openzl/zl_compress.h"
#include "openzl/zl_compressor.h"
#include "openzl/zl_decompress.h"
#include "openzl/zl_graph_api.h"
#include "openzl/zl_localParams.h"

extern "C" {
#include "openzl/compress/graphs/sddl2/sddl2.h"
}

#include "sddl2_parse_test_data.h"

namespace {

/**
 * Compress using SDDL2_parse with bytecode parameter
 */
static size_t compress_sddl2(
        void* dst,
        size_t dstCapacity,
        const void* src,
        size_t srcSize,
        const void* bytecode,
        size_t bytecode_size)
{
    assert(dstCapacity >= ZL_compressBound(srcSize));

    ZL_CCtx* const cctx = ZL_CCtx_create();
    assert(cctx);

    // Set format version (required parameter)
    ZL_Report const fvr = ZL_CCtx_setParameter(
            cctx, ZL_CParam_formatVersion, ZL_MAX_FORMAT_VERSION);
    EXPECT_EQ(ZL_isError(fvr), 0) << "Failed to set format version";

    ZL_Compressor* const cgraph = ZL_Compressor_create();
    assert(cgraph);

    // Register SDDL2_parse with bytecode as local parameter
    ZL_RefParam bytecodeParam = { SDDL2_BYTECODE_PARAM,
                                  bytecode,
                                  bytecode_size };

    ZL_LocalRefParams refParams = { .refParams   = &bytecodeParam,
                                    .nbRefParams = 1 };

    ZL_LocalParams params = { .intParams = { nullptr, 0 },
                              .refParams = refParams };

    ZL_Type inputType                     = ZL_Type_serial;
    ZL_FunctionGraphDesc const sddl2_desc = { .name           = "sddl2_parse",
                                              .graph_f        = SDDL2_parse,
                                              .inputTypeMasks = &inputType,
                                              .nbInputs       = 1,
                                              .lastInputIsVariable = false,
                                              .localParams         = params };

    ZL_GraphID sddl2_gid =
            ZL_Compressor_registerFunctionGraph(cgraph, &sddl2_desc);
    EXPECT_NE(sddl2_gid.gid, ZL_GRAPH_ILLEGAL.gid)
            << "Failed to register SDDL2_parse";

    ZL_Report const rcgr = ZL_CCtx_refCompressor(cctx, cgraph);
    EXPECT_EQ(ZL_isError(rcgr), 0) << "CGraph reference failed\n";

    ZL_Report const r = ZL_CCtx_compress(cctx, dst, dstCapacity, src, srcSize);
    if (ZL_isError(r)) {
        const char* errCtx = ZL_CCtx_getErrorContextString(cctx, r);
        EXPECT_EQ(ZL_isError(r), 0) << "compression failed\nError context: "
                                    << (errCtx ? errCtx : "none");
        ZL_Compressor_free(cgraph);
        ZL_CCtx_free(cctx);
        return 0;
    }

    ZL_Compressor_free(cgraph);
    ZL_CCtx_free(cctx);

    return ZL_validResult(r);
}

/**
 * Decompress
 */
static size_t
decompress(void* dst, size_t dstCapacity, const void* src, size_t srcSize)
{
    ZL_Report const dr = ZL_getDecompressedSize(src, srcSize);
    assert(!ZL_isError(dr));
    size_t const dstSize = ZL_validResult(dr);
    assert(dstCapacity >= dstSize);
    (void)dstSize;

    ZL_DCtx* const dctx = ZL_DCtx_create();
    assert(dctx);

    ZL_Report const r =
            ZL_DCtx_decompress(dctx, dst, dstCapacity, src, srcSize);
    EXPECT_EQ(ZL_isError(r), 0) << "decompression failed \n";

    ZL_DCtx_free(dctx);

    return ZL_validResult(r);
}

/**
 * Round-trip test helper
 */
static void roundtrip_test(
        const void* input,
        size_t inputSize,
        const void* bytecode,
        size_t bytecode_size,
        const char* testName)
{
    size_t const compressedBound = ZL_compressBound(inputSize);
    void* const compressed       = malloc(compressedBound);
    assert(compressed);

    size_t const compressedSize = compress_sddl2(
            compressed,
            compressedBound,
            input,
            inputSize,
            bytecode,
            bytecode_size);
    EXPECT_GT(compressedSize, 0u) << testName << ": compression returned 0";

    void* const decompressed = malloc(inputSize);
    assert(decompressed);

    size_t const decompressedSize =
            decompress(decompressed, inputSize, compressed, compressedSize);
    EXPECT_EQ(decompressedSize, inputSize)
            << testName << ": decompressed size mismatch";

    EXPECT_EQ(std::memcmp(decompressed, input, inputSize), 0)
            << testName << ": decompressed data doesn't match input";

    free(decompressed);
    free(compressed);
}

/**
 * Test: Single U8 typed segment
 *
 * Assembly source (test_data/single_u8_segment.asm):
 *   push.tag 0
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2ParseTest, SingleU8Segment)
{
    std::array<uint8_t, 4> input = { 0xAA, 0xBB, 0xCC, 0xDD };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::SINGLE_U8_SEGMENT.data(),
            sddl2_parse_test_data::SINGLE_U8_SEGMENT.size(),
            "SingleU8Segment");
}

/**
 * Test: Single I32LE typed segment
 *
 * Assembly source (test_data/single_i32le_segment.asm):
 *   push.tag 100
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2ParseTest, SingleI32LESegment)
{
    std::array<uint8_t, 4> input = { 0x2A, 0x00, 0x00, 0x00 }; // 42 in LE

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::SINGLE_I32LE_SEGMENT.data(),
            sddl2_parse_test_data::SINGLE_I32LE_SEGMENT.size(),
            "SingleI32LESegment");
}

/**
 * Test: BYTES segment (no conversion)
 *
 * Assembly source (test_data/bytes_segment.asm):
 *   push.i32 5
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2ParseTest, BytesSegmentNoConversion)
{
    std::array<uint8_t, 5> input = { 'H', 'e', 'l', 'l', 'o' };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::BYTES_SEGMENT.data(),
            sddl2_parse_test_data::BYTES_SEGMENT.size(),
            "BytesSegmentNoConversion");
}

/**
 * Test: Mixed type segments (U8, I32LE, BYTES)
 *
 * Assembly source (test_data/mixed_segments.asm):
 *   # Segment 1: U8[4]
 *   push.tag 1
 *   push.type.u8
 *   push.i32 4
 *   segment.create_tagged
 *
 *   # Segment 2: I32LE[1]
 *   push.tag 2
 *   push.type.i32le
 *   push.i32 1
 *   segment.create_tagged
 *
 *   # Segment 3: BYTES[4]
 *   push.i32 4
 *   segment.create_unspecified
 *   halt
 */
TEST(SDDL2ParseTest, MixedTypeSegments)
{
    std::array<uint8_t, 12> input = {
        0xAA, 0xBB, 0xCC, 0xDD, // Segment 1
        0x2A, 0x00, 0x00, 0x00, // Segment 2
        0x01, 0x02, 0x03, 0x04  // Segment 3
    };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::MIXED_SEGMENTS.data(),
            sddl2_parse_test_data::MIXED_SEGMENTS.size(),
            "MixedTypeSegments");
}

/**
 * Test: U16BE big-endian segment
 *
 * Assembly source (test_data/u16be_segment.asm):
 *   push.tag 50
 *   push.type.u16be
 *   push.i32 4
 *   segment.create_tagged
 *   halt
 */
TEST(SDDL2ParseTest, U16BESegmentBigEndian)
{
    std::array<uint8_t, 8> input = { 0x12, 0x34, 0x56, 0x78,
                                     0xAB, 0xCD, 0xEF, 0x01 };

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::U16BE_SEGMENT.data(),
            sddl2_parse_test_data::U16BE_SEGMENT.size(),
            "U16BESegmentBigEndian");
}

/**
 * Test: Array type segment (U32LE[10])
 *
 * Tests the type.fixed_array opcode in end-to-end compression/decompression.
 * This validates that array types correctly integrate with SDDL2_parse and
 * that segment size calculation accounts for the array width field.
 *
 * Creates a segment containing 25 arrays, where each array is U32LE[10].
 * Total size: 25 × 10 × 4 bytes = 1000 bytes
 *
 * Assembly source (test_data/array_type_u32le_10.asm):
 *   push.tag 100
 *   push.type.u32le       ; Base type: Type{U32LE, 1}
 *   push.i32 10           ; Push array count onto stack
 *   type.fixed_array      ; Stack-based: pops count and type, creates
 * Type{U32LE, 10} push.i32 25           ; Element count: 25 arrays
 *   segment.create_tagged ; Creates 1000-byte segment (25 × 10 × 4 bytes)
 *   halt
 *
 * This creates a segment with type U32LE[10]:
 *   - kind: SDDL2_TYPE_U32LE
 *   - width: 10 (array of 10 U32LE values = 40 bytes per array)
 *   - Total size: 25 arrays × 40 bytes/array = 1000 bytes
 */
TEST(SDDL2ParseTest, ArrayTypeU32LE10)
{
    // Generate 25 arrays of 10 U32LE values each
    // Each array contains values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] in
    // little-endian
    const size_t ARRAY_SIZE = 10;
    const size_t NUM_ARRAYS = 25;

    uint32_t input[NUM_ARRAYS][ARRAY_SIZE];

    // Fill with repeating pattern: each array contains [0..9]
    for (size_t array_idx = 0; array_idx < NUM_ARRAYS; array_idx++) {
        for (size_t i = 0; i < ARRAY_SIZE; i++) {
            uint32_t value      = static_cast<uint32_t>(i);
            input[array_idx][i] = value;
        }
    }

    roundtrip_test(
            input,
            sizeof(input),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.data(),
            sddl2_parse_test_data::ARRAY_TYPE_U32LE_10.size(),
            "ArrayTypeU32LE10");
}

/**
 * Test: Structure array segment
 *
 * Tests the type.structure opcode in end-to-end compression/decompression.
 * This validates that structure types correctly integrate with SDDL2_parse and
 * that structure splitting, field type conversion, and independent compression
 * work correctly in a full round-trip scenario.
 *
 * Creates a segment containing 10 structures, where each structure is:
 *   {U8, I16LE, I32LE}
 * Total size: 10 × (1 + 2 + 4) bytes = 70 bytes
 *
 * Assembly source (test_data/struct_array_segment.asm):
 *   push.tag 200
 *   push.type.u8          ; Field 0: U8
 *   push.type.i16le       ; Field 1: I16LE
 *   push.type.i32le       ; Field 2: I32LE
 *   push.i32 3            ; 3 members
 *   type.structure        ; Creates Type{STRUCTURE{U8, I16LE, I32LE}, width=7}
 *   push.i32 10           ; Element count: 10 structures
 *   segment.create_tagged ; Creates 70-byte segment
 *   halt
 *
 * This tests the full structure split pipeline:
 *   1. SDDL2_parse() recognizes STRUCTURE type segment
 *   2. sddl2_apply_structure_split() decomposes into 3 field arrays:
 *      - Field 0: [10 × U8]   → Convert to U8   → COMPRESS_GENERIC
 *      - Field 1: [10 × I16LE] → Convert to I16LE → COMPRESS_GENERIC
 *      - Field 2: [10 × I32LE] → Convert to I32LE → COMPRESS_GENERIC
 *   3. Each field is independently compressed
 *   4. Decompression reconstructs the original structure layout
 */
TEST(SDDL2ParseTest, StructureArraySegment)
{
    // Generate 10 structures of {U8, I16LE, I32LE}
    const size_t NUM_STRUCTS = 10;

    // Pack structures as byte array (no padding)
    // Structure layout: [U8:1][I16LE:2][I32LE:4] = 7 bytes per struct
    std::vector<uint8_t> input(NUM_STRUCTS * 7);

    for (size_t i = 0; i < NUM_STRUCTS; i++) {
        size_t offset = i * 7;

        // Field 0: U8 (1 byte)
        uint8_t field0    = static_cast<uint8_t>(i * 10 + 1);
        input[offset + 0] = field0;

        // Field 1: I16LE (2 bytes, little-endian)
        int16_t field1    = static_cast<int16_t>(i * 100 + 42);
        input[offset + 1] = static_cast<uint8_t>(field1 & 0xFF);
        input[offset + 2] = static_cast<uint8_t>((field1 >> 8) & 0xFF);

        // Field 2: I32LE (4 bytes, little-endian)
        int32_t field2    = static_cast<int32_t>(i * 1000 + 12345);
        input[offset + 3] = static_cast<uint8_t>(field2 & 0xFF);
        input[offset + 4] = static_cast<uint8_t>((field2 >> 8) & 0xFF);
        input[offset + 5] = static_cast<uint8_t>((field2 >> 16) & 0xFF);
        input[offset + 6] = static_cast<uint8_t>((field2 >> 24) & 0xFF);
    }

    roundtrip_test(
            input.data(),
            input.size(),
            sddl2_parse_test_data::STRUCT_ARRAY_SEGMENT.data(),
            sddl2_parse_test_data::STRUCT_ARRAY_SEGMENT.size(),
            "StructureArraySegment");
}

} // namespace
