# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("../defs.bzl", "relative_headers", "zs_library")

oncall("data_compression")

zs_library(
    name = "custom_parsers",
    srcs = [
        "dependency_registration.cpp",
    ],
    headers = {"custom_parsers/dependency_registration.h": "dependency_registration.h", "dependency_registration.h": "dependency_registration.h"},
    deps = [
        "..:zstronglib",
        "../cpp:openzl_cpp",
        "csv:csv_parser",
        "parquet:parquet_graph",
        "safetensors:safetensors_parser",
        "shared_components:clustering",
    ],
)

cpp_library(
    # @autodeps-skip
    name = "zip_lexer",
    srcs = ["zip_lexer.c"],
    headers = relative_headers(["zip_lexer.h"]) | {"zip_lexer.h": "zip_lexer.h"},
    header_namespace = "",
    deps = [
        "..:zstronglib",
    ],
)

cpp_library(
    # @autodeps-skip
    name = "pytorch_model_parser",
    srcs = ["pytorch_model_parser.c"],
    headers = relative_headers(["pytorch_model_parser.h"]) | {"pytorch_model_parser.h": "pytorch_model_parser.h"},
    header_namespace = "",
    deps = [
        "..:zstronglib",
        ":zip_lexer",
    ],
)

cpp_binary(
    # @autodeps-skip
    name = "pytorch_model_compressor",
    srcs = [
        "pytorch_model_compressor.cpp",
    ],
    deps = [
        "..:zstronglib",
        "../tools:zstrong_cpp",
        ":pytorch_model_parser",
        "//folly:file_util",
        "//folly/init:init",
    ],
)
