// Copyright (c) Meta Platforms, Inc. and affiliates.

#ifndef OPENZL_COMPRESS_SELECTORS_TRANSFORMER_GENERIC_NUMERIC_OPS_H
#define OPENZL_COMPRESS_SELECTORS_TRANSFORMER_GENERIC_NUMERIC_OPS_H

typedef enum {
    TRS_GENERIC_NUMERIC_OP_INVALID  = -1,
    TRS_GENERIC_NUMERIC_OP_CONSTANT = 0,
    TRS_GENERIC_NUMERIC_OP_BITPACK,
    TRS_GENERIC_NUMERIC_OP_DELTA_INT,
    TRS_GENERIC_NUMERIC_OP_DIVIDE_BY_GCD,
    TRS_GENERIC_NUMERIC_OP_ENTROPY,
    TRS_GENERIC_NUMERIC_OP_FIELD_LZ,
    TRS_GENERIC_NUMERIC_OP_FSE,
    TRS_GENERIC_NUMERIC_OP_RANGE_PACK,
    TRS_GENERIC_NUMERIC_OP_SPARSE_NUM,
    TRS_GENERIC_NUMERIC_OP_STORE,
    TRS_GENERIC_NUMERIC_OP_TOKENIZE_NUMERIC,
    TRS_GENERIC_NUMERIC_OP_TOKENIZE_NUMERIC_SORTED,
    TRS_GENERIC_NUMERIC_OP_ZSTD,
    TRS_GENERIC_NUMERIC_OP_COUNT,
} TRS_GenericNumericOpId;

#define TRS_GENERIC_NUMERIC_MAX_OPERATION_COUNT TRS_GENERIC_NUMERIC_OP_COUNT
#endif /* OPENZL_COMPRESS_SELECTORS_TRANSFORMER_GENERIC_NUMERIC_OPS_H */
