# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "cli_util",
    srcs = [
        "parse.cpp",
    ],
    headers = {"cli/utils/parse.h": "parse.h", "parse.h": "parse.h"},
)

zs_cxxlibrary(
    name = "profile_graphs",
    srcs = ["profile_graphs.cpp"],
    headers = {"cli/utils/profile_graphs.h": "profile_graphs.h", "profile_graphs.h": "profile_graphs.h"},
    exported_deps = [
        "../..:zstronglib",
    ],
)

zs_cxxlibrary(
    name = "utils",
    srcs = [
        "compress_profiles.cpp",
        "util.cpp",
    ],
    headers = {
        "cli/utils/compress_profiles.h": "compress_profiles.h",
        "cli/utils/util.h": "util.h",
        "compress_profiles.h": "compress_profiles.h",
        "util.h": "util.h",
    },
    deps = [
        "../..:zstronglib",
        "../../cpp:openzl_cpp",
        "../../custom_parsers:custom_parsers",
        "../../custom_parsers:pytorch_model_parser",
        "../../custom_parsers/csv:csv_parser",
        "../../custom_parsers/parquet:parquet_graph",
        "../../custom_parsers/safetensors:safetensors_parser",
        "../../custom_parsers/sddl:profile",
        "../../custom_parsers/shared_components:clustering",
        "../../tools:arg",
        "../../tools:io",
        "../../tools:logger",
        "../../tools/sddl/compiler:lib",
        "../../tools/sddl2/assembler:lib",
        "../../tools/sddl2/compiler:lib",
        "../../tools/training/ace:automated_compressor_explorer",
        ":profile_graphs",
    ],
    exported_deps = [
        ":cli_util",
    ],
)
